[TEST] fail faster?

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -72,10 +72,12 @@ install:
   - |
     if [[ $TRAVIS_OS_NAME == linux ]]; then
       if [[ $TRAVIS_COMMIT_MESSAGE == *"[TEST]"* ]]; then
+        set -e  # fail fast: https://github.com/travis-ci/travis-ci/issues/1066
         ./codestyle_checks.sh
         mkdir build
         pushd build && cmake .. && make -j2 && file ./bin/bigartm && popd
         pushd python && python setup.py install && popd
+        set +e  # fail slow
       fi
     fi
   - python3 -m pip install cibuildwheel==1.3.0
@@ -84,7 +86,9 @@ before_script:
   - |
     if [[ $TRAVIS_COMMIT_MESSAGE == *"[TEST]"* ]]; then
       if [[ $TRAVIS_OS_NAME == linux ]]; then
+        set -e  # fail fast: https://github.com/travis-ci/travis-ci/issues/1066
         pushd test_data && ./download_datasets.sh && popd
+        set +e  # fail slow
       fi
     fi
 
@@ -104,9 +108,11 @@ script:
   - |
     if [[ $TRAVIS_OS_NAME == linux ]]; then
       if [[ $TRAVIS_COMMIT_MESSAGE == *"[TEST]"* ]]; then
+        set -e  # fail fast: https://github.com/travis-ci/travis-ci/issues/1066
         export ARTM_SHARED_LIBRARY=`pwd`/build/lib/libartm.so
         export BIGARTM_UNITTEST_DATA=`pwd`/test_data
         pushd build && make test ARGS="-V" && popd
+        set +e  # fail slow
       fi
     fi
 
